import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { toNum } from '@/lib/utils';

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const client = await prisma.client.findUnique({
    where: { id: params.id },
    include: { entities: { orderBy: { name: 'asc' } } },
  });

  if (!client) return NextResponse.json({ error: 'Not found' }, { status: 404 });

  const communications = await prisma.communication.findMany({
    where: { clientName: client.name },
    orderBy: { communicationDate: 'desc' },
    take: 20,
  });

  const relationships = await prisma.relationship.findMany({
    where: { OR: [{ sourceId: client.id }, { targetId: client.id }] },
    orderBy: { createdAt: 'desc' },
  });

  const d = (v: any) => v ? toNum(v) : null;
  const dt = (v: Date | null | undefined) => v?.toISOString().slice(0, 10) ?? null;

  const firstEntity = client.entities[0];
  const recentActivity = [
    { id: `a-${client.id}-1`, action: 'Uploaded', subject: `${client.name} Q1 investor letter`, timestamp: '2h ago', user: client.teamLead ?? 'Team Lead', icon: 'uploaded', href: '#' },
    { id: `a-${client.id}-2`, action: 'Scheduled', subject: `quarterly review with ${client.name}`, timestamp: 'Yesterday', user: client.teamLead ?? 'Team Lead', icon: 'scheduled', href: '#' },
    { id: `a-${client.id}-3`, action: 'Completed', subject: `KYC refresh for ${client.name}`, timestamp: '2d ago', user: 'Compliance', icon: 'completed', href: '#' },
    ...(firstEntity ? [{ id: `a-${client.id}-4`, action: 'Added entity', subject: firstEntity.name, timestamp: '4d ago', user: 'Ops', icon: 'created', href: `/data-vault/entities/${firstEntity.entityId}` }] : []),
    { id: `a-${client.id}-5`, action: 'Logged call', subject: `with ${client.teamLead ?? 'primary contact'}`, timestamp: '1w ago', user: client.teamLead ?? 'Team Lead', icon: 'communication', href: '#' },
    { id: `a-${client.id}-6`, action: 'Assigned', subject: `new pod lead to ${client.name}`, timestamp: '2w ago', user: 'Admin', icon: 'assigned', href: '#' },
    { id: `a-${client.id}-7`, action: 'Recorded', subject: `fee invoice for ${client.name}`, timestamp: '3w ago', user: 'Finance', icon: 'transaction', href: '#' },
  ];

  return NextResponse.json({
    client: {
      id: client.id,
      name: client.name,
      shortName: client.shortName,
      primaryStrategy: client.primaryStrategy,
      hqCity: client.hqCity,
      hqCountry: client.hqCountry,
      region: client.region,
      relationshipStart: dt(client.relationshipStart),
      status: client.status,
      totalEntities: client.totalEntities,
      totalNavMm: d(client.totalNavMm),
      totalCommitmentMm: d(client.totalCommitmentMm),
      revenueL12m: d(client.revenueL12m),
      marginPct: d(client.marginPct),
      teamLead: client.teamLead,
      podId: client.podId,
      serviceLine: client.serviceLine,
      yearFounded: client.yearFounded,
      employeeCount: client.employeeCount,
      website: client.website,
      notes: client.notes,
      createdAt: client.createdAt.toISOString(),
      // ── STRATEGY & AUM ──
      aumMm: client.aumMm,
      strategyMix: client.strategyMix,
      portfolioCompanyCount: client.portfolioCompanyCount,
      typicalDealSizeMm: client.typicalDealSizeMm,
      firstFundVintage: client.firstFundVintage,
      latestFundVintage: client.latestFundVintage,
      // ── FUND STRUCTURE ──
      waterfallType: client.waterfallType,
      hurdleRatePct: client.hurdleRatePct,
      mgmtFeePct: client.mgmtFeePct,
      carriedInterestPct: client.carriedInterestPct,
      gpCommitPct: client.gpCommitPct,
      // ── OPERATIONAL PARTNERS ──
      auditFirm: client.auditFirm,
      legalCounsel: client.legalCounsel,
      primaryCustodian: client.primaryCustodian,
      taxAdvisor: client.taxAdvisor,
      bankingRelationship: client.bankingRelationship,
      dataRoomPlatform: client.dataRoomPlatform,
      // ── COMPLIANCE ──
      secRegistered: client.secRegistered,
      advFilingDate: dt(client.advFilingDate),
      formPfRequired: client.formPfRequired,
      amlRiskTier: client.amlRiskTier,
      // ── RELATIONSHIP / CRM ──
      relationshipStage: client.relationshipStage,
      churnDate: dt(client.churnDate),
      churnReason: client.churnReason,
      lastContactAt: dt(client.lastContactAt),
      nextMeetingAt: dt(client.nextMeetingAt),
      accountExecutive: client.accountExecutive,
      nps: client.nps,
      // ── SERVICE MIX ──
      usesFundAdmin: client.usesFundAdmin,
      usesInvestorPortal: client.usesInvestorPortal,
      usesTaxServices: client.usesTaxServices,
      usesComplianceSupport: client.usesComplianceSupport,
      usesTreasuryServices: client.usesTreasuryServices,
      // ── BILLING ──
      billingFrequency: client.billingFrequency,
      arAgingDays: client.arAgingDays,
      lastInvoiceAt: dt(client.lastInvoiceAt),
      paymentMethod: client.paymentMethod,
      // ── ESG ──
      esgPolicy: client.esgPolicy,
      diversityReporting: client.diversityReporting,
      sasbAligned: client.sasbAligned,
      // ── v2 EXPANSION: IR & FUNDRAISING ──
      activeFundraise: client.activeFundraise,
      currentFundTargetMm: client.currentFundTargetMm,
      currentFundRaisedMm: client.currentFundRaisedMm,
      currentFundCloseDate: dt(client.currentFundCloseDate),
      fundraisingCycle: client.fundraisingCycle,
      placementAgent: client.placementAgent,
      subscriptionDocsVersion: client.subscriptionDocsVersion,
      avgLpCommitmentMm: client.avgLpCommitmentMm,
      lpCount: client.lpCount,
      institutionalLpPct: client.institutionalLpPct,
      // ── PORTFOLIO ANALYTICS ──
      grossIrrAggregatePct: client.grossIrrAggregatePct,
      netIrrAggregatePct: client.netIrrAggregatePct,
      tvpiAggregate: client.tvpiAggregate,
      dpiAggregate: client.dpiAggregate,
      moicAggregate: client.moicAggregate,
      realizedPctOfCapital: client.realizedPctOfCapital,
      writeoffCount: client.writeoffCount,
      impairmentCount: client.impairmentCount,
      topQuartilePerformer: client.topQuartilePerformer,
      benchmarkPercentile: client.benchmarkPercentile,
      // ── LP BASE ──
      lpBaseDiversity: client.lpBaseDiversity,
      top3LpConcentrationPct: client.top3LpConcentrationPct,
      pensionLpPct: client.pensionLpPct,
      endowmentLpPct: client.endowmentLpPct,
      sovereignWealthLpPct: client.sovereignWealthLpPct,
      insuranceLpPct: client.insuranceLpPct,
      familyOfficeLpPct: client.familyOfficeLpPct,
      fofLpPct: client.fofLpPct,
      individualHnwLpPct: client.individualHnwLpPct,
      reupRatePct: client.reupRatePct,
      // ── RISK SCORING ──
      creditRiskTier: client.creditRiskTier,
      concentrationRiskTier: client.concentrationRiskTier,
      operationalRiskTier: client.operationalRiskTier,
      cyberRiskTier: client.cyberRiskTier,
      regulatoryRiskTier: client.regulatoryRiskTier,
      litigationPending: client.litigationPending,
      litigationCount: client.litigationCount,
      sanctionsExposure: client.sanctionsExposure,
      keyPersonRiskFlag: client.keyPersonRiskFlag,
      reputationRiskTier: client.reputationRiskTier,
      // ── TECH STACK ──
      accountingSystemPref: client.accountingSystemPref,
      crmSystem: client.crmSystem,
      portalProvider: client.portalProvider,
      reportingPlatform: client.reportingPlatform,
      dataWarehouse: client.dataWarehouse,
      workflowTools: client.workflowTools,
      docMgmtPlatform: client.docMgmtPlatform,
      emailPlatform: client.emailPlatform,
      apiIntegrations: client.apiIntegrations,
      techModernizationScore: client.techModernizationScore,
      // ── FUND ECONOMICS DETAIL ──
      crystallizationFrequency: client.crystallizationFrequency,
      europeanHurdleType: client.europeanHurdleType,
      catchUpType: client.catchUpType,
      catchUpPct: client.catchUpPct,
      clawbackProvision: client.clawbackProvision,
      keyPersonProvision: client.keyPersonProvision,
      noFaultDivorce: client.noFaultDivorce,
      mgmtFeeDiscountPct: client.mgmtFeeDiscountPct,
      preferredReturnCompounding: client.preferredReturnCompounding,
      gpCommitSource: client.gpCommitSource,
      // ── SERVICE SLA ──
      quarterlyReportingSlaDays: client.quarterlyReportingSlaDays,
      annualAuditSlaDays: client.annualAuditSlaDays,
      capitalCallTurnaroundHours: client.capitalCallTurnaroundHours,
      distributionProcessingDays: client.distributionProcessingDays,
      navDeliveryDays: client.navDeliveryDays,
      k1DeliveryTarget: client.k1DeliveryTarget,
      investorInquiryResponseHours: client.investorInquiryResponseHours,
      onboardingTimelineWeeks: client.onboardingTimelineWeeks,
      slaBreachCountYtd: client.slaBreachCountYtd,
      slaOnTimePct: client.slaOnTimePct,
      // ── JSQ FINANCIALS ──
      arrContractedMm: client.arrContractedMm,
      pipelineValueMm: client.pipelineValueMm,
      lifetimeRevenueMm: client.lifetimeRevenueMm,
      lifetimeValueMm: client.lifetimeValueMm,
      costToServiceMm: client.costToServiceMm,
      grossMarginPct: client.grossMarginPct,
      profitabilityTier: client.profitabilityTier,
      upsellOpportunityMm: client.upsellOpportunityMm,
      discountPct: client.discountPct,
      contractValueMm: client.contractValueMm,
      // ── RELATIONSHIP HISTORY ──
      firstMeetingDate: dt(client.firstMeetingDate),
      contractSignedDate: dt(client.contractSignedDate),
      lastContractRenewalDate: dt(client.lastContractRenewalDate),
      nextContractRenewalDate: dt(client.nextContractRenewalDate),
      contractAutoRenew: client.contractAutoRenew,
      prevAdminBeforeJsq: client.prevAdminBeforeJsq,
      referralSource: client.referralSource,
      advocacyScore: client.advocacyScore,
      relationshipOwnerTenureMonths: client.relationshipOwnerTenureMonths,
      renewalRiskScore: client.renewalRiskScore,
      // ── DEI / CULTURE ──
      womenOwnedPct: client.womenOwnedPct,
      minorityOwnedPct: client.minorityOwnedPct,
      diverseLeadershipPct: client.diverseLeadershipPct,
      diversityHiringPledge: client.diversityHiringPledge,
      ilpaDiversityMetrics: client.ilpaDiversityMetrics,
      boardIndependencePct: client.boardIndependencePct,
      governanceCertification: client.governanceCertification,
      paritySignatory: client.paritySignatory,
      rockefellerPrinciples: client.rockefellerPrinciples,
      pcpSignatory: client.pcpSignatory,
      // ── REGULATORY DETAIL ──
      formAdvPart1Date: dt(client.formAdvPart1Date),
      formAdvPart2Date: dt(client.formAdvPart2Date),
      mifidApplicable: client.mifidApplicable,
      aifmdApplicable: client.aifmdApplicable,
      uboRegistryFiled: client.uboRegistryFiled,
      beneficialOwnershipDisclosed: client.beneficialOwnershipDisclosed,
      ccoOnStaff: client.ccoOnStaff,
      ccoName: client.ccoName,
      mostRecentSecExamDate: dt(client.mostRecentSecExamDate),
      secExamDeficiencies: client.secExamDeficiencies,
      // ── COMMUNICATION PREFS ──
      preferredReportingFormat: client.preferredReportingFormat,
      preferredCommunicationChannel: client.preferredCommunicationChannel,
      mainContactFrequency: client.mainContactFrequency,
      escalationPath: client.escalationPath,
      boardMeetingCadence: client.boardMeetingCadence,
      lpAdvisoryCommitteeCount: client.lpAdvisoryCommitteeCount,
      monthlyInvestorUpdateEnabled: client.monthlyInvestorUpdateEnabled,
      privateIrPortalEnabled: client.privateIrPortalEnabled,
      investorDayCadence: client.investorDayCadence,
      roadshowFrequency: client.roadshowFrequency,
    },
    entities: client.entities.map((e) => ({
      entityId: e.entityId,
      name: e.name,
      entityType: e.entityType,
      assetClass: e.assetClass,
      strategy: e.strategy,
      vintage: e.vintage,
      navMm: d(e.navMm),
      commitmentMm: d(e.commitmentMm),
      lifecycleStatus: e.lifecycleStatus,
      scopeStatus: e.scopeStatus,
      dataQualityScore: d(e.dataQualityScore),
    })),
    communications: communications.map((c) => ({
      id: c.id,
      channel: c.channel,
      direction: c.direction,
      subject: c.subject,
      summary: c.summary,
      fromName: c.fromName,
      toName: c.toName,
      entityName: c.entityName,
      sentiment: c.sentiment,
      urgency: c.urgency,
      status: c.status,
      communicationDate: c.communicationDate.toISOString(),
      followUpDate: dt(c.followUpDate),
    })),
    relationships: relationships.map((r) => ({
      id: r.id,
      sourceId: r.sourceId,
      targetId: r.targetId,
      relationshipType: (r as any).relationshipType ?? (r as any).type ?? null,
      description: (r as any).description ?? null,
      strength: (r as any).strength ?? null,
    })),
    recentActivity,
  });
}
