import { NextRequest, NextResponse } from 'next/server';
import ExcelJS from 'exceljs';

export const runtime = 'nodejs';

// Standard DIU schema columns
const DIU_COLUMNS = [
  'Legal Entity',
  'Vehicle',
  'Investor',
  'JSQ Position ID',
  'Transaction Date',
  'Effective Date',
  'Transaction Type',
  'Debit/Credit',
  'Amount',
  'Currency',
  'Account Ref',
  'Memo',
  'External Ref',
];

interface ExportRow {
  [key: string]: string | number | null;
}

export async function POST(req: NextRequest) {
  const { rows, legalEntity, context } = await req.json() as {
    rows: ExportRow[];
    legalEntity?: string;
    context?: string;
  };

  if (!rows || !Array.isArray(rows)) {
    return NextResponse.json({ error: 'rows array is required' }, { status: 400 });
  }

  const wb = new ExcelJS.Workbook();
  wb.creator = 'Canopy DIU Mapper';
  wb.created = new Date();

  const ws = wb.addWorksheet('DIU Data');
  const headerStyle: Partial<ExcelJS.Style> = {
    font: { bold: true, color: { argb: 'FFFFFFFF' } },
    fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1B3A4B' } },
    alignment: { horizontal: 'center' },
  };

  // Use columns from first row if available, else use standard DIU columns
  const cols = rows.length > 0 ? Object.keys(rows[0]) : DIU_COLUMNS;
  ws.columns = cols.map((c) => ({ header: c, key: c, width: Math.max(c.length + 4, 16) }));
  ws.getRow(1).eachCell((cell) => Object.assign(cell, headerStyle));

  for (const row of rows) {
    ws.addRow(row);
  }

  // Skip sheet
  const wsSkip = wb.addWorksheet('SKIP_Macro Logs');
  wsSkip.addRow(['Generated by Canopy DIU Mapper', new Date().toISOString()]);

  const buf = await wb.xlsx.writeBuffer();
  const entity = legalEntity ?? (rows.find((r) => r['Legal Entity'])?.['Legal Entity'] as string) ?? 'Unknown';
  const today = new Date();
  const dateStr = `${today.getFullYear()}.${String(today.getMonth() + 1).padStart(2, '0')}.${String(today.getDate()).padStart(2, '0')}`;
  const contextLabel = context ?? 'Investran DIU';
  const safeName = `${entity} - ${dateStr} - ${contextLabel}.xlsx`.replace(/[\\/*?:"<>|]/g, '');

  return new NextResponse(buf, {
    status: 200,
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'Content-Disposition': `attachment; filename="${safeName}"`,
    },
  });
}
